// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4QAUY2ozaCC736kbb5iNJ50LvbrMoUs',
    appId: '1:869883649464:web:8bc568f98593be1502834d',
    messagingSenderId: '869883649464',
    projectId: 'scientry-raannakasturi',
    authDomain: 'scientry-raannakasturi.firebaseapp.com',
    storageBucket: 'scientry-raannakasturi.firebasestorage.app',
    measurementId: 'G-FWZ6CXH88K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB354u8juQjhtP-d_7Ei9_IpTdeZ7LlQqU',
    appId: '1:869883649464:android:47be2b431307954b02834d',
    messagingSenderId: '869883649464',
    projectId: 'scientry-raannakasturi',
    storageBucket: 'scientry-raannakasturi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENjJ4uMkJH1g_pCGunUoFQdU8LlrfHts',
    appId: '1:869883649464:ios:4eb2c60d66e5cdd502834d',
    messagingSenderId: '869883649464',
    projectId: 'scientry-raannakasturi',
    storageBucket: 'scientry-raannakasturi.firebasestorage.app',
    iosBundleId: 'eu.org.raannakasturi.scientry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENjJ4uMkJH1g_pCGunUoFQdU8LlrfHts',
    appId: '1:869883649464:ios:4eb2c60d66e5cdd502834d',
    messagingSenderId: '869883649464',
    projectId: 'scientry-raannakasturi',
    storageBucket: 'scientry-raannakasturi.firebasestorage.app',
    iosBundleId: 'eu.org.raannakasturi.scientry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4QAUY2ozaCC736kbb5iNJ50LvbrMoUs',
    appId: '1:869883649464:web:4087d4b972831dce02834d',
    messagingSenderId: '869883649464',
    projectId: 'scientry-raannakasturi',
    authDomain: 'scientry-raannakasturi.firebaseapp.com',
    storageBucket: 'scientry-raannakasturi.firebasestorage.app',
    measurementId: 'G-0WPP2TR5H2',
  );
}
